### ISSUE TITLE
Font downloader script sources are broken.

### ISSUE THREAD

**Issue by reo6** [aib/MPv2#1]
https://github.com/notofonts/noto-fonts/raw/master/hinted/NotoSansSymbols2/NotoSansSymbols2-Regular.ttf
https://github.com/googlefonts/noto-fonts/raw/master/hinted/NotoMusic/NotoMusic-Regular.ttf
https://github.com/google/roboto/raw/master/src/hinted/Roboto-Regular.ttf

The repos still exist but those links are broken.

**Comment by aib** [comment]
Fixed in #2
